FROM python:3.10-slim-bullseye

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install \
    ca-certificates \
    --no-install-recommends -y

RUN pip install -U pip

WORKDIR /app
