FROM python:3.10-slim-bullseye

ARG DEBIAN_FRONTEND=noninteractive

ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update \
    && apt-get install \
    ca-certificates \
    --no-install-recommends -y

COPY requirements-dev.txt .

RUN pip install --no-deps -r requirements-dev.txt
