version: "3.7"

services:

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - CI
    volumes:
      - '.:/app'
    working_dir: '/app'
    entrypoint: []

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-ghcr.io/harrison-ai/cobalt-purestorage-credentials-rotator}:local
    entrypoint: []
    volumes:
      - './output:/output'
    command:
      - rotate-fb-creds

  smoketest:
    image: ${IMAGE_NAME:-ghcr.io/harrison-ai/cobalt-purestorage-credentials-rotator}:local
    entrypoint: []
    command:
      - smoketest
