name: CI Workflow

on:
  push:

  release:
      types: [published]

env:
  CI: true
  IMAGE_REPO: ghcr.io/harrison-ai/cobalt-purestorage-credentials-rotator

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build dev container
        run: make build-dev

      - name: run formatting checks
        run: make fmt

      - name: run unit tests
        run: make test

      - name: build app container - Build the shippable image
        run: make build-app

      - name: smoketest - Ensure the shippable image has built correctly
        run: make smoketest

      - name: get short sha
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> ${GITHUB_ENV}
        if: github.event_name != 'release'

      - name: log into github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: publish docker image - non release
        run: make publish
        if: github.event_name == 'push'
        env:
          IMAGE_NAME: ${{ env.IMAGE_REPO }}
          IMAGE_TAG: ${{ env.SHORT_SHA }}

      - name: publish docker image - release
        run: make publish-release
        if: github.event_name == 'release'
        env:
          IMAGE_NAME: ${{ env.IMAGE_REPO }}
          IMAGE_TAG: ${{ github.ref_name }}
