name: CI Workflow

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # - name: build docker container
      #   run: make docker-build
      #   working-directory: flashblade-creds-rotator

      - name: run unit tests
        run: make test
