name: CI Workflow

on:
  push:

env:
  CI: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # - naame: run formatting checks
      #   run: make check

      - name: run unit tests
        run: make test
